"""Render curriculum registries and the source-mapped interview coverage table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTATION_SOURCE = ROOT / "curriculum" / "notation.json"
GLOSSARY_SOURCE = ROOT / "curriculum" / "glossary.json"
MANIFEST_SOURCE = ROOT / "curriculum" / "manifest.json"
NOTATION_OUTPUT = ROOT / "tex" / "common" / "notation.tex"
GLOSSARY_OUTPUT = ROOT / "tex" / "common" / "glossary.tex"
PREREQUISITE_OUTPUT = ROOT / "tex" / "generated" / "prerequisites"
COURSE_MAP_OUTPUT = ROOT / "tex" / "generated" / "course-map.tex"
CONCEPT_INDEX_OUTPUT = ROOT / "tex" / "generated" / "concept-index.tex"
LOWER_CONCEPT_INDEX_OUTPUT = ROOT / "tex" / "generated" / "lower-concept-index.tex"
LOWER_ROUTE_BRIDGES_OUTPUT = ROOT / "tex" / "generated" / "lower-route-bridges.tex"
INTERVIEW_LEDGER_SOURCE = ROOT / "curriculum" / "interview-problem-ledger.json"
INTERVIEW_OUTPUT = ROOT / "tex" / "generated" / "interview-problem-coverage.tex"


def tex_text(value: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "#": r"\#",
        "_": r"\_",
    }
    return "".join(replacements.get(character, character) for character in value)


def first_teaching(unit_id: str, unit_metadata: dict[str, tuple[str, str]]) -> str:
    if unit_id == "foundation.oracle-smoke":
        return "最小证据实验"
    if ".ch" in unit_id:
        volume, chapter = unit_id.split(".ch", maxsplit=1)
        volume_name = {"upper": "上册", "lower": "下册"}[volume]
        return f"{volume_name}第 {int(chapter)} 章"
    volume, title = unit_metadata[unit_id]
    volume_name = {"upper": "上册", "lower": "下册"}[volume]
    return f"{volume_name}“{tex_text(title)}”"


def render_notation(
    unit_metadata: dict[str, tuple[str, str]], unit_order: dict[str, int]
) -> str:
    registry = json.loads(NOTATION_SOURCE.read_text(encoding="utf-8"))
    rows = []
    for entry in sorted(registry["symbols"], key=lambda item: unit_order[item["first_unit"]]):
        rows.append(
            f"${entry['symbol']}$ & {tex_text(entry['meaning'])} & "
            f"{first_teaching(entry['first_unit'], unit_metadata)} \\\\"
        )
    body = "\n".join(rows)
    return (
        "% Generated by tools/build_course_assets.py; do not edit by hand.\n"
        "\\begin{longtable}{p{0.24\\textwidth}p{0.50\\textwidth}p{0.18\\textwidth}}\n"
        "\\toprule\n"
        "符号 & 含义 & 首次正式教学 \\\\\n"
        "\\midrule\n"
        "\\endfirsthead\n"
        "\\toprule\n"
        "符号 & 含义 & 首次正式教学 \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{longtable}\n\n"
        "机器可读的权威注册位于课程清单引用的 notation registry；本表由注册表确定性生成。\n"
    )


def render_glossary() -> str:
    registry = json.loads(GLOSSARY_SOURCE.read_text(encoding="utf-8"))
    items = []
    for entry in registry["terms"]:
        zh = tex_text(entry["zh"])
        en = tex_text(entry["en"])
        label = zh if zh == en else f"{zh}（{en}）"
        items.append(f"  \\item[{label}] {tex_text(entry['definition'])}")
    body = "\n".join(items)
    return (
        "% Generated by tools/build_course_assets.py; do not edit by hand.\n"
        "\\begin{description}\n"
        f"{body}\n"
        "\\end{description}\n"
    )


def prerequisite_name(identifier: str, titles: dict[str, str]) -> str:
    if ".ch" in identifier:
        volume, chapter = identifier.split(".ch", maxsplit=1)
        volume_name = {"upper": "上册", "lower": "下册"}[volume]
        return f"{volume_name}第 {int(chapter)} 章《{tex_text(titles[identifier])}》"
    volume = "上册" if identifier.startswith("upper.") else "下册"
    return f"{volume}《{tex_text(titles[identifier])}》"


def render_prerequisites(unit: dict[str, object], titles: dict[str, str]) -> str:
    prerequisites = [str(value) for value in unit.get("prerequisites", [])]
    if not prerequisites:
        description = "无；只需本书前言声明的读者基础。"
    else:
        rendered = [prerequisite_name(identifier, titles) for identifier in prerequisites]
        description = "、".join(rendered) + "。"
    return (
        "% Generated from curriculum/manifest.json; do not edit by hand.\n"
        f"\\item 直接先修：{description}\n"
    )


def chapter_number(unit_id: str) -> int:
    return int(unit_id.split(".ch", maxsplit=1)[1])


def render_course_map(manifest: dict[str, object]) -> str:
    units = [
        unit
        for unit in manifest["units"]
        if str(unit["id"]).startswith("upper.ch") and not unit.get("internal", False)
    ]
    titles = {str(unit["id"]): str(unit["title"]) for unit in units}
    route_sections = []
    for route in manifest["reading_routes"]:
        chain = r" $\rightarrow$ ".join(
            f"第 {chapter_number(identifier)} 章" for identifier in route["units"]
        )
        route_sections.append(
            f"\\subsection*{{{tex_text(str(route['title']))}}}\n"
            f"{tex_text(str(route['description']))}\n\n{chain}\n"
        )

    rows = []
    for unit in units:
        prerequisites = [str(value) for value in unit.get("prerequisites", [])]
        prerequisite_text = "无" if not prerequisites else "、".join(
            f"第 {chapter_number(identifier)} 章" for identifier in prerequisites
        )
        route_tags = [
            str(route["title"])
            for route in manifest["reading_routes"]
            if unit["id"] in route["units"]
        ]
        rows.append(
            f"{chapter_number(str(unit['id']))} & {tex_text(titles[str(unit['id'])])} & "
            f"{prerequisite_text} & {tex_text('、'.join(route_tags) or '按需')} \\\\"
        )

    bridge_sections = []
    for bridge in manifest["reader_bridges"]:
        route_titles = [
            str(route["title"])
            for route in manifest["reading_routes"]
            if route["id"] in bridge["for_routes"]
        ]
        review = "、".join(
            f"第 {chapter_number(identifier)} 章" for identifier in bridge["review_units"]
        )
        before = chapter_number(str(bridge["before_unit"]))
        bridge_sections.append(
            f"\\subsection*{{{tex_text(str(bridge['title']))}}}\n"
            f"服务路线：{tex_text('、'.join(route_titles))}；在第 {before} 章前学习。"
            f"需要完整证明时回看{review}。\n"
        )

    return (
        "% Generated from curriculum/manifest.json; do not edit by hand.\n"
        "\\section{两条阅读路线}\n\n"
        + "\n\n".join(route_sections)
        + "\n\\begin{note}\n"
        "应用主线不是免修证明条件。遇到概率空间、期望交换、条件化或 $L^p$ 论证时，"
        "按下表回看第 3、4、8 章的对应定义与定理；理论增强线则完整学习这些章节。\n"
        "\\end{note}\n\n"
        "\\section{应用主线桥接}\n\n"
        + "\n".join(bridge_sections)
        + "\n"
        "\\section{完整直接先修图}\n\n"
        "下表把 manifest 中的每条直接先修边完整展开；传递先修可沿行递归追溯。\n\n"
        "\\begin{longtable}{p{0.07\\textwidth}p{0.42\\textwidth}p{0.20\\textwidth}p{0.20\\textwidth}}\n"
        "\\toprule\n章 & 学习单元 & 直接先修 & 路线 \\\\\n\\midrule\n\\endfirsthead\n"
        "\\toprule\n章 & 学习单元 & 直接先修 & 路线 \\\\\n\\midrule\n\\endhead\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{longtable}\n"
    )


def render_concept_index(manifest: dict[str, object]) -> str:
    locations: dict[str, list[int]] = {}
    for unit in manifest["units"]:
        identifier = str(unit["id"])
        if unit.get("internal", False) or not identifier.startswith("upper.ch"):
            continue
        number = chapter_number(identifier)
        evidence = unit.get("evidence", {})
        for term in evidence.get("glossary_terms", []):
            locations.setdefault(str(term), []).append(number)

    rows = []
    for term in sorted(locations, key=lambda value: value.casefold()):
        chapters = "、".join(f"第 {number} 章" for number in sorted(set(locations[term])))
        rows.append(f"{tex_text(term)} & {chapters} \\\\")
    return (
        "% Generated from curriculum/manifest.json; do not edit by hand.\n"
        "\\begin{longtable}{p{0.52\\textwidth}p{0.36\\textwidth}}\n"
        "\\toprule\n主题 & 正式教学位置 \\\\\n"
        "\\midrule\n\\endfirsthead\n"
        "\\toprule\n主题 & 正式教学位置 \\\\\n"
        "\\midrule\n\\endhead\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{longtable}\n"
    )


def render_lower_concept_index(manifest: dict[str, object]) -> str:
    locations: dict[str, list[str]] = {}
    for unit in manifest["units"]:
        if (
            unit.get("internal", False)
            or unit.get("volume") != "lower"
            or not unit.get("published", False)
        ):
            continue
        title = str(unit["title"])
        for term in unit.get("evidence", {}).get("glossary_terms", []):
            locations.setdefault(str(term), []).append(title)
    rows = []
    for term in sorted(locations, key=lambda value: value.casefold()):
        units = "；".join(tex_text(title) for title in dict.fromkeys(locations[term]))
        rows.append(f"{tex_text(term)} & {units} \\\\")
    return (
        "% Generated from curriculum/manifest.json; do not edit by hand.\n"
        "\\begin{longtable}{p{0.30\\textwidth}p{0.60\\textwidth}}\n"
        "\\toprule\n主题 & 正式教学单元 \\\\\n"
        "\\midrule\n\\endfirsthead\n"
        "\\toprule\n主题 & 正式教学单元 \\\\\n"
        "\\midrule\n\\endhead\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{longtable}\n"
    )


def render_lower_route_bridges(manifest: dict[str, object]) -> str:
    titles = {str(unit["id"]): str(unit["title"]) for unit in manifest["units"]}
    rows = []
    for track in manifest["tracks"]:
        prerequisites = []
        for identifier in track["bridge_prerequisites"]:
            prerequisites.append(
                f"\\texttt{{{tex_text(str(identifier))}}}（{tex_text(titles[str(identifier)])}）"
            )
        rows.append(
            f"{tex_text(str(track['title']))} & " + r"；\newline ".join(prerequisites) + r" \\"
        )
    return (
        "% Generated from curriculum/manifest.json; do not edit by hand.\n"
        "\\begin{longtable}{p{0.22\\textwidth}p{0.68\\textwidth}}\n"
        "\\toprule\n路线 & 需要核对的上册学习单元 \\\\\n"
        "\\midrule\n\\endfirsthead\n"
        "\\toprule\n路线 & 需要核对的上册学习单元 \\\\\n"
        "\\midrule\n\\endhead\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{longtable}\n"
    )


def render_interview_coverage() -> str:
    """Render the tracked interview ledger without rebuilding its source data."""

    payload = json.loads(INTERVIEW_LEDGER_SOURCE.read_text(encoding="utf-8"))
    entries = [item for item in payload["problems"] if item.get("home_unit")]
    summary = payload["summary"]
    lines = [
        "% Generated by tools/build_course_assets.py; edit curriculum/interview-problem-ledger.json instead.",
        "\\begin{center}",
        "\\begin{tabular}{lr}",
        f"具名目录条目 & {summary['catalogued']} " + r"\\",
        f"已纳入本书的条目 & {summary['mapped_entries']} " + r"\\",
        f"总题量覆盖率 & {float(summary['coverage']) * 100:.1f}\\% " + r"\\",
        "\\end{tabular}",
        "\\end{center}",
        "本统计以冻结后的 146 个具名目录条目为分母；每条只设一个主归属，交叉引用不重复计数。",
        "\\begin{longtable}{p{0.14\\textwidth}p{0.38\\textwidth}p{0.34\\textwidth}}",
        "编号 & 原书题名 & 本书唯一主归属 " + r"\\ \hline",
    ]
    for item in entries:
        title = str(item["original_title"]).replace("&", "\\&")
        lines.append(f"{item['id']} & {title} & \\path{{{item['home_unit']}}} " + r"\\")
    lines.extend(["\\end{longtable}", ""])
    return "\n".join(lines)


def obsolete_prerequisite_files(expected: dict[Path, str]) -> list[Path]:
    expected_paths = {
        path.resolve()
        for path in expected
        if path.parent.resolve() == PREREQUISITE_OUTPUT.resolve()
    }
    observed = (
        {path.resolve() for path in PREREQUISITE_OUTPUT.glob("*.tex")}
        if PREREQUISITE_OUTPUT.is_dir()
        else set()
    )
    return sorted(observed - expected_paths)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    manifest = json.loads(MANIFEST_SOURCE.read_text(encoding="utf-8"))
    unit_metadata = {
        str(unit["id"]): (str(unit["volume"]), str(unit["title"]))
        for unit in manifest["units"]
    }
    unit_order = {
        str(unit["id"]): index for index, unit in enumerate(manifest["units"])
    }
    titles = {str(unit["id"]): str(unit["title"]) for unit in manifest["units"]}
    upper_units = [
        unit for unit in manifest["units"] if str(unit["id"]).startswith("upper.ch")
    ]
    expected = {
        NOTATION_OUTPUT: render_notation(unit_metadata, unit_order),
        GLOSSARY_OUTPUT: render_glossary(),
        COURSE_MAP_OUTPUT: render_course_map(manifest),
        CONCEPT_INDEX_OUTPUT: render_concept_index(manifest),
        LOWER_CONCEPT_INDEX_OUTPUT: render_lower_concept_index(manifest),
        LOWER_ROUTE_BRIDGES_OUTPUT: render_lower_route_bridges(manifest),
        INTERVIEW_OUTPUT: render_interview_coverage(),
    }
    expected.update(
        {
            PREREQUISITE_OUTPUT
            / f"upper-ch{int(str(unit['id']).removeprefix('upper.ch')):02d}.tex":
            render_prerequisites(unit, titles)
            for unit in upper_units
        }
    )
    expected.update(
        {
            PREREQUISITE_OUTPUT / f"{str(unit['id']).replace('.', '-')}.tex":
            render_prerequisites(unit, titles)
            for unit in manifest["units"]
            if unit.get("volume") == "lower" and unit.get("published", False)
        }
    )
    if args.check:
        stale = [
            path
            for path, content in expected.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        obsolete = obsolete_prerequisite_files(expected)
        if stale or obsolete:
            for path in stale:
                print(f"stale reader registry: {path.relative_to(ROOT).as_posix()}")
            for path in obsolete:
                print(f"obsolete reader registry: {path.relative_to(ROOT).as_posix()}")
            return 1
    else:
        for path in obsolete_prerequisite_files(expected):
            path.unlink()
        for path, content in expected.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")

    notation_count = len(json.loads(NOTATION_SOURCE.read_text(encoding="utf-8"))["symbols"])
    glossary_count = len(json.loads(GLOSSARY_SOURCE.read_text(encoding="utf-8"))["terms"])
    print(
        f"course assets=passed symbols={notation_count} terms={glossary_count} "
        f"interview_entries={len(json.loads(INTERVIEW_LEDGER_SOURCE.read_text(encoding='utf-8'))['problems'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
