from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTATION_SOURCE = ROOT / "curriculum" / "notation.json"
GLOSSARY_SOURCE = ROOT / "curriculum" / "glossary.json"
NOTATION_OUTPUT = ROOT / "tex" / "common" / "notation.tex"
GLOSSARY_OUTPUT = ROOT / "tex" / "common" / "glossary.tex"


def tex_text(value: str) -> str:
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "#": r"\#",
        "_": r"\_",
    }
    return "".join(replacements.get(character, character) for character in value)


def first_teaching(unit_id: str) -> str:
    if unit_id == "foundation.oracle-smoke":
        return "最小证据实验"
    volume, chapter = unit_id.split(".ch", maxsplit=1)
    volume_name = {"upper": "上册", "lower": "下册"}[volume]
    return f"{volume_name}第 {int(chapter)} 章"


def unit_order(unit_id: str) -> tuple[int, int]:
    if unit_id == "foundation.oracle-smoke":
        return (0, 0)
    volume, chapter = unit_id.split(".ch", maxsplit=1)
    return ({"upper": 1, "lower": 2}[volume], int(chapter))


def render_notation() -> str:
    registry = json.loads(NOTATION_SOURCE.read_text(encoding="utf-8"))
    rows = []
    for entry in sorted(registry["symbols"], key=lambda item: unit_order(item["first_unit"])):
        rows.append(
            f"${entry['symbol']}$ & {tex_text(entry['meaning'])} & "
            f"{first_teaching(entry['first_unit'])} \\\\"
        )
    body = "\n".join(rows)
    return (
        "% Generated by tools/render_shared_registries.py; do not edit by hand.\n"
        "\\begin{longtable}{p{0.24\\textwidth}p{0.50\\textwidth}p{0.18\\textwidth}}\n"
        "\\toprule\n"
        "符号 & 含义 & 首次正式教学 \\\\\n"
        "\\midrule\n"
        "\\endfirsthead\n"
        "\\toprule\n"
        "符号 & 含义 & 首次正式教学 \\\\\n"
        "\\midrule\n"
        "\\endhead\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{longtable}\n\n"
        "机器可读的权威注册位于课程清单引用的 notation registry；本表由注册表确定性生成。\n"
    )


def render_glossary() -> str:
    registry = json.loads(GLOSSARY_SOURCE.read_text(encoding="utf-8"))
    items = []
    for entry in registry["terms"]:
        label = f"{tex_text(entry['zh'])}（{tex_text(entry['en'])}）"
        items.append(f"  \\item[{label}] {tex_text(entry['definition'])}")
    body = "\n".join(items)
    return (
        "% Generated by tools/render_shared_registries.py; do not edit by hand.\n"
        "\\begin{description}\n"
        f"{body}\n"
        "\\end{description}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = {
        NOTATION_OUTPUT: render_notation(),
        GLOSSARY_OUTPUT: render_glossary(),
    }
    if args.check:
        stale = [
            path
            for path, content in expected.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            for path in stale:
                print(f"stale reader registry: {path.relative_to(ROOT).as_posix()}")
            return 1
    else:
        for path, content in expected.items():
            path.write_text(content, encoding="utf-8", newline="\n")

    notation_count = len(json.loads(NOTATION_SOURCE.read_text(encoding="utf-8"))["symbols"])
    glossary_count = len(json.loads(GLOSSARY_SOURCE.read_text(encoding="utf-8"))["terms"])
    print(f"reader registries=passed symbols={notation_count} terms={glossary_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
